### PR TITLE
Enhance runtime onMessage sendResponse type by adding one any parameter

### PR DESCRIPTION
**Pull request by FaXaq**
Hi,

I've been toying around with this package but I've encountered a type issue regarding `browser.runtime.onMessage`, `sendResponse` type. As per this link : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage we should be able to use this function with a parameter (of an uncertain type though).

I've added it as `any` since it's how you're already typing it with `sendMessage`.

Thank you for the package though, it's really nice

### CODE REVIEW

**Review by Lusito — CHANGES_REQUESTED** [review]
Thanks for the PR. Looks alright from what I can see. Not sure why I didn't add this myself.
Just two things I'd like to see changed before merging:

- Could you do the same for onMessageExternal? That should behave the same way.
- Some of the changes have been unrelated to this PR (updated schema files). I've updated them in the master branch. Could you merge the latest changes? That should reduce this PR to the relevant parts.

Thanks!

**Comment by FaXaq** [comment]
There you go, it should do it ! Thanks for the comments.

**Review by Lusito — APPROVED** [review]

**Comment by Lusito** [comment]
Thanks!

**Comment by aklinker1** [comment]
@Lusito This hasn't been released to `@types/webextension-polyfill` yet, right? Anything I can do to help?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webextension-polyfill/namespaces/runtime.d.ts

**Pull request merged**
