### PR TITLE
Fix return type of browser.dns.resolve()

### PR DESCRIPTION
**Pull request by nilfalse**
This PR introduces a fix to [`browser.dns.resolve()`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve) where `void` return type had previously been incorrectly inferred.

https://github.com/Lusito/webextension-polyfill-ts/blob/ae930cb8b859d90236502aa2a70bc02a9ee322aa/lib/dns.d.ts#L33-L42

I've also included a few small drive-by changes:
- Updated contents of `schemas/runtime.json` with the most recent downloaded version.
- Removed duplicate call to `removeUnsupported` in `src/fixes/index.ts`.

### CODE REVIEW

**Comment by Lusito** [comment]
Thanks. This is almost ready to be merged:
The changes of schemas/runtime.json has not been adapted to the generated files yet. When I run "npm run all" on your branch, I get a different manifest.d.ts file. Would you mind updating your PR to fix this?

**Comment by nilfalse** [comment]
:white_check_mark: I just merged your `master` into this branch.

`npm run all` should no longer diverge. I just didn't commit the file to avoid potential git conflicts with the other PR.

**Comment by Lusito** [comment]
Thanks!

**Comment by Lusito** [comment]
New version has been released

**Pull request merged**
