### PR TITLE
updated Port.postMessage definition

### PR DESCRIPTION
**Pull request by bboydflo**
updated one definition according to this docs https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/Port

### CODE REVIEW

**Comment by Lusito** [comment]
Well done, thanks!

**Comment by bboydflo** [comment]
You welcome! 

I have double checked and I am a little bit in doubt I put the type correctly. Check this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/98030c7c5ab431f03d666b3bc524feaea96d8452/types/chrome/index.d.ts#L5041 what do you think?

**Comment by Lusito** [comment]
Not 100% sure, but I think that any message that is valid json can be passed as argument. Just like it is with [sendMessage ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage). So null, number, string, etc. would all be valid.

Aside from that:
- There is no API at this moment, where an object can be passed, that is defined as anything else than `any`.
- Even if you where to make the type `Object` (as seen in your link), there would be no type-checking. You can pass string, number and boolean (not null tho). to function(message: Object).
- So if an object is required, `object` needs to be used instead. 

As long as we're not 100% sure, that an object must be passed and other values are invalid, we might break valid code, so I'd leave it like this.

**Comment by bboydflo** [comment]
good 👍

**Comment by Lusito** [comment]
@bboydflo I just created an introduction for contributors.. it seems you figured it out yourself, but since this was already the second pull request, I think it might be useful at some point:

https://github.com/Lusito/webextension-polyfill-ts/blob/master/CONTRIBUTING.md

Let me know if there is anything you think I should add.

**Comment by bboydflo** [comment]
The original documentation was fine enough to make a simple fix but the new docs are well written! Thanks!

**Pull request merged**
